#!/bin/sh
# chkconfig: - 85 15
# description: start/stop unicorn script.
# processname: unicorn_rails
### BEGIN INIT INFO
# Provides:          unicorn_rails
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: unicorn
### END INIT INFO

PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin

NAME="unicorn"
ENV=production

ROOT_DIR="/home/apprunner/bootcampsns"

PID="${ROOT_DIR}/tmp/pids/unicorn.pid"
CONF="${ROOT_DIR}/config/unicorn.rb"
CMD="bundle exec unicorn_rails -c ${CONF} -E ${ENV} -D"
USER=apprunner

start()
{
  if [ -e $PID ]; then
    echo "$NAME already started"
    exit 1
  fi
  echo "start $NAME"
  cd $ROOT_DIR
  su -c "$CMD" $USER
}

stop()
{
  if [ ! -e $PID ]; then
    echo "$NAME not started"
    exit 1
  fi
  echo "stop $NAME"
  su -c "kill -QUIT `cat ${PID}`" $USER
  su -c "rm -f $PID" $USER
}

status()
{
  if [ ! -e $PID ]; then
    echo "$NAME is not running"
  else
    echo "$NAME is running"
  fi
}

force_stop()
{
  if [ ! -e $PID ]; then
    echo "$NAME not started"
    exit 1
  fi
  echo "stop $NAME"
  su -c "kill -INT `cat ${PID}`" $USER
  su -c "rm -f $PID" $USER
}

reload()
{
  if [ ! -e $PID ]; then
    echo "$NAME not started"
    start
    exit 0
  fi
  echo "reload $NAME"
  su -c "kill -HUP `cat ${PID}`" $USER
}

restart()
{
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  force-stop)
    force_stop
    ;;
  reload)
    reload
    ;;
  restart)
    restart
    ;;
  *)
    echo "Syntax Error: release [start|stop|force-stop|reload|restart]"
    ;;
esac
