---
uid_map:
  mrkn: 1001
  nishioka: 1002
  mitsuyoshi: 1003
  hashimoto: 1004
  hatappi: 1005
  suthio: 1006
  yamaura: 1007
  amano: 1008
  yoshida: 1009
  kawakubox: 1010
  miyachik: 1011
  nishaya: 1012
  tei: 1013
  iida: 1014
  ihara: 1015
  yokoi: 1016
  kotaro: 1017
  yhatt: 1018
  bino98: 1019
  nyamadori: 1020
  takanamito: 1021
  morioka: 1022
  toshihiro: 1023
  anochick: 1024
  manchose: 1025
  gfx: 1026
  satoshi: 1027
  nishimunea: 1100
  yonashiro: 1101
  katsuya: 1102
  shimizu: 1103
